export const elementList = {
  HEADERS_LIST: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'],
  ALL_CLASSES: [
    '.mutation-alert-div',
    '.fa-circle-xmark',
    '.fa-circle-question',
    '.bulb-icon-general-errors-div',
  ],
  MANDATORY_TAGS_BEFORE_H2: '<h1>',
  MANDATORY_TAGS_BEFORE_H3: '<h1>, <h2>',
  MANDATORY_TAGS_BEFORE_H4: '<h1>, <h2>, <h3>',
  MANDATORY_TAGS_BEFORE_H5: '<h1>, <h2>, <h3>, <h4>',
  MANDATORY_TAGS_BEFORE_H6: '<h1>, <h2>, <h3>, <h4>, <h5>',
  INVALID_TAGS_BEFORE_H1: ['h2', 'h3', 'h4', 'h5', 'h6'],
  INVALID_TAGS_BEFORE_H2: ['h3', 'h4', 'h5', 'h6'],
  INVALID_TAGS_BEFORE_H3: ['h4', 'h5', 'h6'],
  INVALID_TAGS_BEFORE_H4: ['h5', 'h6'],
  INVALID_TAGS_BEFORE_H5: ['h6'],
  MANDATORY_TAGS_BEFORE_H2_SET: ['<h1>'],
  MANDATORY_TAGS_BEFORE_H3_SET: ['<h1>', '<h2>'],
  MANDATORY_TAGS_BEFORE_H4_SET: ['<h1>', '<h2>', '<h3>'],
  MANDATORY_TAGS_BEFORE_H5_SET: ['<h1>', '<h2>', '<h3>', '<h4>'],
  MANDATORY_TAGS_BEFORE_H6_SET: ['<h1>', '<h2>', '<h3>', '<h4>', '<h5>'],
  VALID_HEADER_PARENTS: ['body', 'article', 'section', 'main', 'head', 'html'],
  VALID_FOOTER_PARENTS: ['body', 'section', 'article', 'main', 'html'],
  VALID_ASIDE_PARENTS: ['body', 'main', 'section', 'article'],
  VALID_NAV_PARENTS: ['html', 'header', 'body', 'main', 'section', 'html'],
  DIV_WRAPPER_CHILDREN: [
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'p',
    'span',
    'div',
    'img',
    'ul',
    'li',
    'a',
  ],
  FOOTER_VALID_NEXT_ELEMENTS: ['script', 'style', 'link', 'template'],
  VALID_ASIDE_CHILDREN: [
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'p',
    'span',
    'a',
    'i',
    'img',
    'b',
    'em',
  ],
  VALID_NAV_CHILDREN: ['ol', 'ul', 'li', 'a'],
  SEMANTIC_STANDARDS_LINK:
    'https://dom-traverser-extension.netlify.app/semantics/standards',
  DENSITY_STANDARDS_LINK:
    'https://dom-traverser-extension.netlify.app/density/configuration',
  USAGE_VIDEO_LINK:
    'https://drive.google.com/file/d/1Qnc9sTqCCzbjlUCUXiBKQM47M-NbmeLG/view?usp=sharing',
  W3C_API_LINK: 'https://validator.w3.org/nu/?out=json&doc=',
  DEPRECATED_TAGS: [
    'applet',
    'basefont',
    'big',
    'center',
    'font',
    'frame',
    'frameset',
    'noframes',
    'strike',
    'tt',
    'u',
    'marquee',
  ],
  VALID_SECTION_PARENTS: ['article', 'section', 'body', 'main', 'html'],
}

export const elementTags = {
  HTML: 'html',
  BODY: 'body',
  HEAD: 'head',
  MAIN: 'main',
  DIV: 'div',
  SPAN: 'span',
  H1: 'h1',
  H2: 'h2',
  H3: 'h3',
  H4: 'h4',
  H5: 'h5',
  H6: 'h6',
  PARA: 'p',
  ANCHOR: 'a',
  ARTICLE: 'article',
  HEADER: 'header',
  FOOTER: 'footer',
  SECTION: 'section',
  ASIDE: 'aside',
  DETAILS: 'details',
  SUMMARY: 'summary',
  TIME: 'time',
  NAV: 'nav',
  FIGURE: 'figure',
  FIGURE_CAPTION: 'figcaption',
  BR: 'br',
  HR: 'hr',
  IMG: 'img',
  INPUT: 'input',
  FORM: 'form',
  BUTTON: 'button',
  AUDIO: 'audio',
  VIDEO: 'video',
  LI: 'li',
  OL: 'ol',
  UL: 'ul',
  SOURCE: 'source',
  TRACK: 'track',
}

export enum Direction {
  TOP = 'top',
  BOTTOM = 'bottom',
  LEFT = 'left',
  RIGHT = 'right',
}

export const stylesList = {
  COLOR: 'color',
  ZERO_OPACITY_BLACK: 'rgba(0, 0, 0, 0)',
  BORDER_COLOR: 'border-color',
  BACKGROUND_COLOR: 'background-color',
  DISPLAY: 'display',
  VISIBILITY: 'visibility',
}

export const attributesList = {
  DATETIME: 'datetime',
  TYPE: 'type',
  NAME: 'name',
  ID: 'id',
  ACTION: 'action',
  SUBMIT: 'submit',
  KIND: 'kind',
}

export const pageNames = {
  POPUP: 'popup',
  CONTENT_SCRIPT: 'content-script',
  BACKGROUND: 'background',
  SEMANTIC: 'semantic',
}

export const msgSubjects = {
  TRAVERSE_DOM: 'traverse-dom',
  CHECK_STYLES: 'check-styles',
  CHECK_DENSITY: 'check-density',
  OPEN_FORM: 'open-form',
  HIGHLIGHT_ELEMENT: 'highlight-element',
}

export const alertColors = {
  SUCCESS: 'success',
  DANGER: 'danger',
}
